language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script: cmake CMakeLists.txt

script: make
